Add notifications in views for member add/edit/remove
IMGIITRoorkee/omniport-service-groups pull request #1
Opened 2019-12-29 11:35 UTC by aru31

@pradumangoyal

2020-01-04 09:36 UTC, dhruvkb requested changes

2020-01-04 09:36 UTC, dhruvkb commented on utils/get_category.py
> +    """
Documentation is missing. This does not qualify as documentation.

2020-01-04 09:36 UTC, dhruvkb commented on utils/get_category.py
> +    service_name = settings.DISCOVERY.get_app_configuration('groups').nomenclature.name
Is this within 80 characters?

2020-01-04 09:36 UTC, dhruvkb commented on views/membership.py
> +from rest_framework.response import Response
Import `response` from DRF and use `response.Response` wherever. Makes imports much cleaner.

2020-01-05 21:24 UTC, dhruvkb requested changes
https://github.com/IMGIITRoorkee/omniport-service-developer/pull/1#pullrequestreview-338421936 applies here.

2020-01-08 23:07 UTC, dhruvkb commented
Use the same feedback as given in the other PR IMGIITRoorkee/omniport-service-developer#1.

2020-01-11 11:44 UTC, ayushjn20 approved these changes

2020-01-11 11:44 UTC, ayushjn20 commented on utils/get_category.py
> +        name=service_name
Shouldn't the category node's name be the `verbose_name` of `groups` service?

2020-01-11 11:44 UTC, ayushjn20 commented on utils/get_category.py
> +        name=service_name
@aru31 Any progress?

2020-01-11 12:18 UTC, aru31 commented on utils/get_category.py
> +        name=service_name
Done

2020-01-11 12:49 UTC, merged